# Generated by Django 3.2 on 2021-09-14 06:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barangay', models.CharField(blank=True, max_length=200, verbose_name='Barangay')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(blank=True, choices=[('District 1', 'District 1'), ('District 2', 'District 2')], max_length=200, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_pasig_incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(blank=True, max_length=200, null=True, verbose_name='City')),
                ('UnitStation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unit/Station')),
                ('CrimeOffense', models.CharField(blank=True, max_length=200, null=True, verbose_name='Crime/Offense')),
                ('Week', models.IntegerField(blank=True, null=True, verbose_name='Week')),
                ('Date', models.DateField(blank=True, max_length=200, null=True, verbose_name='Date')),
                ('Time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('Day', models.CharField(blank=True, max_length=200, null=True, verbose_name='Day')),
                ('Incident_Type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Incident Type')),
                ('Number_of_Persons_Involved', models.IntegerField(blank=True, null=True, verbose_name='# of Persons Involved')),
                ('Light', models.CharField(blank=True, max_length=200, null=True, verbose_name='Light')),
                ('Weather', models.CharField(blank=True, max_length=200, null=True, verbose_name='Weather')),
                ('Case_Status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Case Status')),
                ('Address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('Along_Avenue', models.CharField(blank=True, max_length=200, null=True, verbose_name='Along Avenue')),
                ('Corner_Avenue', models.CharField(blank=True, max_length=200, null=True, verbose_name='Corner Avenue')),
                ('Along_Road', models.CharField(blank=True, max_length=200, null=True, verbose_name='Along Road')),
                ('Corner_Road', models.CharField(blank=True, max_length=200, null=True, verbose_name='Corner Road')),
                ('Along_Street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Along Street')),
                ('Corner_Street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Corner Street')),
                ('Bound', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bound')),
                ('Along_Highway', models.CharField(blank=True, max_length=200, null=True, verbose_name='Along Highway')),
                ('Corner_Highway', models.CharField(blank=True, max_length=200, null=True, verbose_name='Corner Highway')),
                ('Along_Boulevard', models.CharField(blank=True, max_length=200, null=True, verbose_name='Along Boulevard')),
                ('Corner_Boulevard', models.CharField(blank=True, max_length=200, null=True, verbose_name='Corner Boulevard')),
                ('Others', models.CharField(blank=True, max_length=200, null=True, verbose_name='Others')),
                ('Surface_Condition', models.CharField(blank=True, max_length=200, null=True, verbose_name='Surface Condition')),
                ('Surface_Type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Surface Type')),
                ('Road_Class', models.CharField(blank=True, max_length=200, null=True, verbose_name='Road Class')),
                ('Road_Repair', models.CharField(blank=True, max_length=200, null=True, verbose_name='Road Repair')),
                ('Hit_and_Run', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hit and Run')),
                ('Road_Character', models.CharField(blank=True, max_length=200, null=True, verbose_name='Road Character')),
                ('Suspect_Name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Name')),
                ('Suspect_Severity', models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Severity')),
                ('Suspect_Age', models.CharField(blank=True, max_length=100, null=True, verbose_name='Suspect Age')),
                ('Suspect_Sex', models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Sex')),
                ('Suspect_Civil_Status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Civil_Status')),
                ('Suspect_Address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Address')),
                ('Suspect_Vehicle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Vehicle')),
                ('Suspect_Vehicle_Body_Type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Vehicle_Body_Type')),
                ('Suspect_Plate_No', models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Plate_No')),
                ('Suspect_Reg_Owner', models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Reg_Owner')),
                ('Suspect_Drl_No', models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Drl_No')),
                ('Suspect_Vehicle_Year_Model', models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Vehicle_Year_Model')),
                ('Victim_Type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Type')),
                ('Victim_Name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Name')),
                ('Victim_Severity', models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Severity')),
                ('Victim_Age', models.CharField(blank=True, max_length=100, null=True, verbose_name='Victim Age')),
                ('Victim_Sex', models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Sex')),
                ('Victim_Civil_Status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Civil_Status')),
                ('Victim_Address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Address')),
                ('Victim_Vehicle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Vehicle')),
                ('Victim_Vehicle_Body_Type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Vehicle_Body_Type')),
                ('Victim_Plate_No', models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Plate_No')),
                ('Victim_Reg_Owner', models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Reg_Owner')),
                ('Victim_Drl_No', models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Drl_No')),
                ('Victim_Vehicle_Year_Model', models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Vehicle_Year_Model')),
                ('Narrative', models.CharField(blank=True, max_length=200, null=True, verbose_name='Narrative')),
                ('date_added', models.DateField(blank=True, default=datetime.datetime(2021, 9, 14, 6, 1, 18, 398156, tzinfo=utc), null=True, verbose_name='Date Added')),
                ('added_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='Added By')),
                ('Barangay_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadcast.tbl_barangay')),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadcast.tbl_district')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_barangay',
            name='District_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadcast.tbl_district'),
        ),
    ]
