# Generated by Django 3.2 on 2021-09-14 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 14, 15, 40, 55, 944011, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
    ]
