# Generated by Django 3.2 on 2021-07-07 05:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 5, 36, 15, 940241, tzinfo=utc), verbose_name='Date Added'),
        ),
    ]
