# Generated by Django 3.2 on 2021-09-17 15:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0002_alter_tbl_pasig_incidents_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 17, 15, 17, 43, 939043, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.CreateModel(
            name='Tbl_public_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200, verbose_name='User ID')),
                ('reported_city', models.CharField(blank=True, max_length=200, verbose_name='City:')),
                ('reported_district', models.CharField(blank=True, max_length=200, verbose_name='District')),
                ('reported_location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('reported_along', models.CharField(blank=True, max_length=200, verbose_name='Along')),
                ('reported_corner', models.CharField(blank=True, max_length=200, verbose_name='Corner')),
                ('reported_narrative', models.CharField(blank=True, max_length=200, verbose_name='Narrative')),
                ('reported_image_proof', models.CharField(blank=True, max_length=200, verbose_name='Proof of Incident')),
                ('reported_date_and_time', models.DateTimeField(blank=True, max_length=200, verbose_name='Date Reported')),
                ('read_status', models.CharField(blank=True, max_length=200, verbose_name='Read')),
                ('reported_brgy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadcast.tbl_barangay')),
            ],
        ),
    ]
