# Generated by Django 3.2 on 2021-09-25 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0002_auto_20210925_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_add_members',
            name='Date_Added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 25, 8, 31, 41, 195800, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Along',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Along'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Corner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Corner'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Road_Character',
            field=models.CharField(blank=True, choices=[('Straight Flat', 'Straight Flat'), ('Straight Incline', 'Straight Incline'), ('Curve', 'Curve'), ('Curve Incline', 'Curve Incline'), ('Upwards', 'Upwards'), ('Downwards', 'Downwards')], max_length=200, null=True, verbose_name='Road Character'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 25, 8, 31, 41, 195800, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 25, 8, 31, 41, 195800, tzinfo=utc), verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 9, 25, 8, 31, 41, 195800, tzinfo=utc), verbose_name='Date Reported'),
        ),
    ]
