# Generated by Django 3.2 on 2021-07-07 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0003_auto_20210707_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 5, 42, 16, 493959, tzinfo=utc), verbose_name='Date Added'),
        ),
    ]
