# Generated by Django 3.2 on 2021-09-17 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0003_auto_20210917_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_public_report',
            old_name='read_status',
            new_name='Read_Status',
        ),
        migrations.RenameField(
            model_name='tbl_public_report',
            old_name='reported_along',
            new_name='Reported_Along',
        ),
        migrations.RenameField(
            model_name='tbl_public_report',
            old_name='reported_brgy',
            new_name='Reported_Brgy',
        ),
        migrations.RenameField(
            model_name='tbl_public_report',
            old_name='reported_city',
            new_name='Reported_City',
        ),
        migrations.RenameField(
            model_name='tbl_public_report',
            old_name='reported_corner',
            new_name='Reported_Corner',
        ),
        migrations.RenameField(
            model_name='tbl_public_report',
            old_name='reported_district',
            new_name='Reported_District',
        ),
        migrations.RenameField(
            model_name='tbl_public_report',
            old_name='reported_image_proof',
            new_name='Reported_Image_Proof',
        ),
        migrations.RenameField(
            model_name='tbl_public_report',
            old_name='reported_location',
            new_name='Reported_Location',
        ),
        migrations.RenameField(
            model_name='tbl_public_report',
            old_name='reported_narrative',
            new_name='Reported_Narrative',
        ),
        migrations.RenameField(
            model_name='tbl_public_report',
            old_name='user_id',
            new_name='User_ID',
        ),
        migrations.RemoveField(
            model_name='tbl_public_report',
            name='reported_date_and_time',
        ),
        migrations.AddField(
            model_name='tbl_public_report',
            name='Report_Status',
            field=models.CharField(blank=True, max_length=200, verbose_name='Report Status'),
        ),
        migrations.AddField(
            model_name='tbl_public_report',
            name='Reported_Date_and_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 17, 15, 26, 18, 574951, tzinfo=utc), verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 17, 15, 26, 18, 574951, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
    ]
