# Generated by Django 3.2 on 2021-09-25 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0003_auto_20210925_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Name',
        ),
        migrations.RemoveField(
            model_name='tbl_pasig_incidents',
            name='Victim_Name',
        ),
        migrations.AddField(
            model_name='tbl_pasig_incidents',
            name='Investigator',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Investigator'),
        ),
        migrations.AddField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Fname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect First Name'),
        ),
        migrations.AddField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Lname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Last Name'),
        ),
        migrations.AddField(
            model_name='tbl_pasig_incidents',
            name='Victim_Fname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim First Name'),
        ),
        migrations.AddField(
            model_name='tbl_pasig_incidents',
            name='Victim_Lname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Last Name'),
        ),
        migrations.AlterField(
            model_name='tbl_add_members',
            name='Date_Added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 25, 15, 24, 53, 696368, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 25, 15, 24, 53, 696368, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 25, 15, 24, 53, 696368, tzinfo=utc), verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 9, 25, 15, 24, 53, 696368, tzinfo=utc), verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='tbl_substation',
            name='Substation',
            field=models.CharField(blank=True, choices=[('Pasig City Police Station', 'Pasig City Police Station'), ('Substation 1', 'Substation 1'), ('Substation 2', 'Substation 2'), ('Substation 3', 'Substation 3'), ('Substation 4', 'Substation 4'), ('Substation 5', 'Substation 5'), ('Substation 6', 'Substation 6'), ('Substation 7', 'Substation 7'), ('Substation 8', 'Substation 8')], max_length=200, verbose_name='Substation'),
        ),
    ]
