# Generated by Django 3.2 on 2021-09-18 01:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import roadcast.models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0004_auto_20210917_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 18, 1, 16, 3, 664766, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Date_and_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 18, 1, 16, 3, 664766, tzinfo=utc), verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Image_Proof',
            field=models.ImageField(blank=True, upload_to=roadcast.models.image_path, verbose_name='Proof of Incident'),
        ),
    ]
