# Generated by Django 3.2 on 2021-09-19 04:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0005_auto_20210918_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_public_report',
            name='Recipient',
            field=models.CharField(blank=True, max_length=200, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 19, 4, 35, 14, 162343, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Date_and_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 19, 4, 35, 14, 162343, tzinfo=utc), verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Narrative',
            field=models.CharField(blank=True, max_length=800, verbose_name='Narrative'),
        ),
    ]
