# Generated by Django 3.2 on 2021-07-07 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0005_alter_tbl_pasig_incidents_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='District',
            field=models.CharField(blank=True, choices=[('District 1', 'District 1'), ('District 2', 'District 2')], max_length=200, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Number_of_Persons_Involved',
            field=models.IntegerField(blank=True, verbose_name='# of Persons Involved'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 9, 55, 31, 279220, tzinfo=utc), verbose_name='Date Added'),
        ),
    ]
