# Generated by Django 3.2 on 2021-09-19 09:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0006_auto_20210919_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_public_report',
            name='Reported_Time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 9, 19, 9, 56, 21, 55368, tzinfo=utc), verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 19, 9, 56, 21, 55368, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Date_and_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 19, 9, 56, 21, 55368, tzinfo=utc), verbose_name='Date Reported'),
        ),
    ]
