# Generated by Django 3.2 on 2021-07-07 10:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0006_auto_20210707_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(blank=True, choices=[('District 1', 'District 1'), ('District 2', 'District 2'), ('District 3', 'District 3')], max_length=200, verbose_name='District')),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Day',
            field=models.CharField(blank=True, max_length=200, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 10, 46, 14, 199808, tzinfo=utc), verbose_name='Date Added'),
        ),
        migrations.CreateModel(
            name='Tbl_barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barangay', models.CharField(blank=True, max_length=200, verbose_name='Barangay')),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadcast.tbl_district')),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Barangay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadcast.tbl_barangay'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='District',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadcast.tbl_district'),
        ),
    ]
