# Generated by Django 3.2 on 2021-07-07 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0007_auto_20210707_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_district',
            name='District',
            field=models.CharField(blank=True, choices=[('District 1', 'District 1'), ('District 2', 'District 2')], max_length=200, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 10, 56, 24, 183783, tzinfo=utc), verbose_name='Date Added'),
        ),
    ]
