# Generated by Django 3.2 on 2021-07-08 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0008_auto_20210707_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Age',
            field=models.CharField(blank=True, max_length=100, verbose_name='Suspect Age'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Victim_Age',
            field=models.CharField(blank=True, max_length=100, verbose_name='Victim Age'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 7, 8, 6, 38, 59, 932467, tzinfo=utc), verbose_name='Date Added'),
        ),
    ]
