# Generated by Django 3.2 on 2021-10-14 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0008_auto_20211014_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_add_members',
            name='Date_Added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 14, 8, 45, 11, 554154, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 14, 8, 45, 11, 554154, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 14, 8, 45, 11, 554154, tzinfo=utc), verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 10, 14, 8, 45, 11, 554154, tzinfo=utc), verbose_name='Time Reported'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report_response',
            name='Response_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 14, 8, 45, 11, 554154, tzinfo=utc), null=True, verbose_name='Response Date'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report_response',
            name='Response_Time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 10, 14, 8, 45, 11, 554154, tzinfo=utc), null=True, verbose_name='Response Time'),
        ),
        migrations.AlterField(
            model_name='tbl_substation',
            name='Substation',
            field=models.CharField(blank=True, choices=[('PNP-Pasig', 'PNP-Pasig'), ('Substation 1', 'Substation 1'), ('Substation 2', 'Substation 2'), ('Substation 3', 'Substation 3'), ('Substation 4', 'Substation 4'), ('Substation 5', 'Substation 5'), ('Substation 6', 'Substation 6'), ('Substation 7', 'Substation 7'), ('Substation 8', 'Substation 8')], max_length=200, verbose_name='Substation'),
        ),
    ]
