# Generated by Django 3.2 on 2021-09-26 08:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0008_auto_20210926_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_forecast',
            fields=[
                ('Date', models.DateField(blank=True, max_length=200, primary_key=True, serialize=False, verbose_name='Dates')),
                ('Incidents', models.PositiveIntegerField(blank=True, verbose_name='Incidents')),
                ('Averages', models.FloatField(blank=True, max_length=200, null=True, verbose_name='Averages')),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_add_members',
            name='Date_Added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 26, 8, 44, 36, 962074, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 26, 8, 44, 36, 962074, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 26, 8, 44, 36, 962074, tzinfo=utc), verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 9, 26, 8, 44, 36, 962074, tzinfo=utc), verbose_name='Date Reported'),
        ),
    ]
