# Generated by Django 3.2 on 2021-09-22 10:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0008_auto_20210919_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_public_report',
            name='Assigned_Investigator',
            field=models.CharField(blank=True, max_length=200, verbose_name='Investigator'),
        ),
        migrations.AddField(
            model_name='tbl_public_report',
            name='Substation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Substation'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 22, 10, 15, 54, 233576, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 22, 10, 15, 54, 233576, tzinfo=utc), verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 9, 22, 10, 15, 54, 233576, tzinfo=utc), verbose_name='Date Reported'),
        ),
    ]
