# Generated by Django 3.2 on 2021-07-08 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0009_auto_20210708_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 7, 8, 6, 39, 42, 367188, tzinfo=utc), verbose_name='Date Added'),
        ),
    ]
