# Generated by Django 3.2 on 2021-07-08 12:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0011_alter_tbl_pasig_incidents_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Week',
            field=models.IntegerField(blank=True, null=True, verbose_name='Week'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 7, 8, 12, 29, 44, 559395, tzinfo=utc), verbose_name='Date Added'),
        ),
    ]
