# Generated by Django 3.2 on 2021-10-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0012_auto_20211025_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Date',
            field=models.DateField(auto_now_add=True, verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Time',
            field=models.TimeField(auto_now_add=True, verbose_name='Time Reported'),
        ),
    ]
