# Generated by Django 3.2 on 2021-10-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0014_auto_20211025_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Assigned_Investigator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadcast.tbl_add_members'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Substation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Substation_id', to='roadcast.tbl_substation'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report_response',
            name='Report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Report_id', to='roadcast.tbl_public_report'),
        ),
    ]
