# Generated by Django 3.2 on 2021-09-28 04:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0015_auto_20210928_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_public_report_response',
            name='Response_Time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 28, 4, 42, 32, 256113, tzinfo=utc), null=True, verbose_name='Response Time'),
        ),
        migrations.AlterField(
            model_name='tbl_add_members',
            name='Date_Added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 28, 4, 42, 32, 256113, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 28, 4, 42, 32, 256113, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 28, 4, 42, 32, 256113, tzinfo=utc), verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 9, 28, 4, 42, 32, 256113, tzinfo=utc), verbose_name='Time Reported'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report_response',
            name='Response_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 28, 4, 42, 32, 256113, tzinfo=utc), null=True, verbose_name='Response Date'),
        ),
    ]
