# Generated by Django 3.2 on 2021-07-08 12:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0015_alter_tbl_pasig_incidents_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Along_Avenue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Along Avenue'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Along_Boulevard',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Along Boulevard'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Along_Highway',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Along Highway'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Along_Road',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Along Road'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Along_Street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Along Street'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Bound',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bound'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Case_Status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Case Status'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='City',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Corner_Avenue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Corner Avenue'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Corner_Boulevard',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Corner Boulevard'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Corner_Highway',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Corner Highway'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Corner_Road',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Corner Road'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Corner_Street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Corner Street'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='CrimeOffense',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Crime/Offense'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Date',
            field=models.DateField(blank=True, max_length=200, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Day',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Hit_and_Run',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hit and Run'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Incident_Type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Incident Type'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Light',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Light'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Narrative',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Narrative'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Number_of_Persons_Involved',
            field=models.IntegerField(blank=True, null=True, verbose_name='# of Persons Involved'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Others',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Others'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Road_Character',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Road Character'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Road_Class',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Road Class'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Road_Repair',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Road Repair'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Surface_Condition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Surface Condition'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Surface_Type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Surface Type'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Address'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Suspect Age'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Civil_Status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Civil_Status'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Drl_No',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Drl_No'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Name'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Plate_No',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Plate_No'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Reg_Owner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Reg_Owner'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Severity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Severity'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Sex',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Sex'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Vehicle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Vehicle'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Vehicle_Body_Type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Vehicle_Body_Type'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Vehicle_Year_Model',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Suspect Vehicle_Year_Model'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='UnitStation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unit/Station'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Victim_Address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Address'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Victim_Age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Victim Age'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Victim_Civil_Status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Civil_Status'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Victim_Drl_No',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Drl_No'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Victim_Name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Name'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Victim_Plate_No',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Plate_No'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Victim_Reg_Owner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Reg_Owner'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Victim_Severity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Severity'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Victim_Sex',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Sex'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Victim_Type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Type'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Victim_Vehicle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Vehicle'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Victim_Vehicle_Body_Type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Vehicle_Body_Type'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Victim_Vehicle_Year_Model',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Victim Vehicle_Year_Model'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Weather',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Weather'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='added_by',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Added By'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 8, 12, 45, 5, 407198, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
    ]
