# Generated by Django 3.2 on 2021-08-01 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0016_auto_20210708_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_barangay',
            old_name='District',
            new_name='District_id',
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 1, 7, 32, 35, 97999, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
    ]
