# Generated by Django 3.2 on 2021-10-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0016_auto_20211025_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_genpub_users',
            name='nf_acc_activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tbl_genpub_users',
            name='nf_new_incident',
            field=models.BooleanField(default=True),
        ),
    ]
