# Generated by Django 3.2 on 2021-09-30 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0013_auto_20210928_1808'),
        ('roadcast', '0017_auto_20210928_1247'),
    ]

    operations = [
    ]
