# Generated by Django 3.2 on 2021-08-19 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0017_auto_20210801_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_pasig_incidents',
            old_name='Barangay',
            new_name='Barangay_id',
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 19, 14, 35, 56, 385080, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
    ]
