# Generated by Django 3.2 on 2021-09-13 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0019_alter_tbl_pasig_incidents_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_add_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Members_Type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Type')),
                ('Members_Substation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Substation')),
                ('Members_District', models.CharField(blank=True, max_length=200, null=True, verbose_name='District')),
                ('Members_Fname', models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name')),
                ('Members_Lname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name')),
                ('Members_Position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Position')),
                ('Members_Dept', models.CharField(blank=True, max_length=200, null=True, verbose_name='Department')),
                ('Members_Email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('Members_Password', models.CharField(blank=True, max_length=200, null=True, verbose_name='Password')),
                ('Members_Pic', models.CharField(blank=True, max_length=200, null=True, verbose_name='Picture')),
                ('Date_Added', models.DateField(blank=True, default=datetime.datetime(2021, 9, 13, 7, 21, 34, 378408, tzinfo=utc), null=True, verbose_name='Date Added')),
                ('Added_By', models.CharField(blank=True, max_length=200, null=True, verbose_name='Added By')),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 13, 7, 21, 34, 378408, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
    ]
