# Generated by Django 3.2 on 2021-10-03 02:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0021_auto_20211001_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_add_members',
            name='Date_Added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 3, 2, 7, 41, 831359, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Suspect_Age',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Suspect Age'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='Victim_Age',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Victim Age'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 3, 2, 7, 41, 831359, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 3, 2, 7, 41, 831359, tzinfo=utc), verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 10, 3, 2, 7, 41, 831359, tzinfo=utc), verbose_name='Time Reported'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report_response',
            name='Response_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 3, 2, 7, 41, 831359, tzinfo=utc), null=True, verbose_name='Response Date'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report_response',
            name='Response_Time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 10, 3, 2, 7, 41, 831359, tzinfo=utc), null=True, verbose_name='Response Time'),
        ),
    ]
