# Generated by Django 3.2 on 2021-11-14 20:38

from django.db import migrations, models
import roadcast.models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0021_alter_tbl_substation_substation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Reported_Image_Proof',
            field=models.ImageField(blank=True, null=True, upload_to=roadcast.models.image_path_incident_report, verbose_name='Proof of Incident'),
        ),
    ]
