# Generated by Django 3.2 on 2021-09-13 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0021_auto_20210913_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_add_members',
            name='Date_Added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 13, 7, 29, 47, 932622, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tbl_pasig_incidents',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 13, 7, 29, 47, 932622, tzinfo=utc), null=True, verbose_name='Date Added'),
        ),
    ]
