# Generated by Django 3.2 on 2021-11-14 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0022_alter_tbl_public_report_reported_image_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_public_report',
            name='Admin_Sender',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Admin Sender'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='User_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadcast.tbl_genpub_users'),
        ),
    ]
