# Generated by Django 3.2 on 2021-11-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0023_auto_20211114_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Admin_Sender',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Admin Sender'),
        ),
    ]
