# Generated by Django 3.2 on 2021-11-14 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0024_alter_tbl_public_report_admin_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Admin_Sender',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Admin Sender'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='User_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadcast.tbl_genpub_users'),
        ),
    ]
