# Generated by Django 3.2 on 2021-11-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0025_auto_20211114_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Admin_Sender',
            field=models.IntegerField(blank=True, null=True, verbose_name='Admin Sender'),
        ),
    ]
