# Generated by Django 3.2 on 2021-11-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0026_alter_tbl_public_report_admin_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_public_report',
            name='Admin_Sender',
        ),
    ]
