# Generated by Django 3.2 on 2021-11-15 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0027_remove_tbl_public_report_admin_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_public_report',
            name='Admin_Sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Admin', to='roadcast.tbl_add_members'),
        ),
    ]
