# Generated by Django 3.2 on 2021-11-15 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0029_alter_tbl_public_report_response_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Admin_Sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadcast.tbl_add_members'),
        ),
        migrations.AlterField(
            model_name='tbl_public_report',
            name='Assigned_Investigator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Inv', to='roadcast.tbl_add_members'),
        ),
    ]
