# Generated by Django 3.2 on 2021-11-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0030_auto_20211115_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_add_members',
            name='Availability',
            field=models.CharField(blank=True, default='Yes', max_length=200, null=True, verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='tbl_add_members',
            name='Day_off',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Day Off'),
        ),
        migrations.AlterField(
            model_name='tbl_genpub_users',
            name='date_signed_up',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
