# Generated by Django 3.2 on 2021-11-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0036_alter_tbl_add_members_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_add_members',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
