# Generated by Django 3.2 on 2021-11-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0037_alter_tbl_add_members_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_add_members',
            name='Archived',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=200, null=True, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='tbl_add_members',
            name='Availability',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=200, null=True, verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='tbl_add_members',
            name='Day_off',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Day Off'),
        ),
    ]
