# Generated by Django 3.2 on 2021-11-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0038_auto_20211127_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_add_members',
            name='Day_off',
            field=models.IntegerField(blank=True, null=True, verbose_name='Day Off (Mon(0) - Sun(6)'),
        ),
    ]
