# Generated by Django 3.2 on 2021-11-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0040_alter_tbl_add_members_day_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_add_members',
            name='nf_brgy',
            field=models.CharField(blank=True, choices=[('Bagong Ilog', 'Bagong Ilog'), ('Bagong Katipunan', 'Bagong Katipunan'), ('Bambang', 'Bambang'), ('Buting', 'Buting'), ('Caniogan', 'Caniogan'), ('Dela Paz', 'Dela Paz'), ('Kalawaan', 'Kalawaan'), ('Kapasigan', 'Kapasigan'), ('Kapitolyo', 'Kapitolyo'), ('Malinao', 'Malinao'), ('Manggahan', 'Manggahan'), ('Maybunga', 'Maybunga'), ('Oranbo', 'Oranbo'), ('Palatiw', 'Palatiw'), ('Pinagbuhatan', 'Pinagbuhatan'), ('Pineda', 'Pineda'), ('Rosario', 'Rosario'), ('Sagad', 'Sagad'), ('San Antonio', 'San Antonio'), ('San Joaquin', 'San Joaquin'), ('San Jose', 'San Jose'), ('San Miguel', 'San Miguel'), ('San Nicolas', 'San Nicolas'), ('Santa Lucia', 'Santa Lucia'), ('Santa Rosa', 'Santa Rosa'), ('Santa Tomas', 'Santa Tomas'), ('Santa Lucia', 'Santa Lucia'), ('Santolan', 'Santolan'), ('Sumilang', 'Sumilang'), ('Ugong', 'Ugong')], max_length=50, null=True),
        ),
    ]
