# Generated by Django 3.2 on 2021-11-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadcast', '0041_alter_tbl_add_members_nf_brgy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_public_report_response',
            name='Response',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Response'),
        ),
    ]
